### ISSUE TITLE
Company Ticket in the planning stage

### ISSUE THREAD

**Issue by Kerp1** [cthdidIT/itbio#138]
When a company ticket is selected to be used in a showing in the planning stage it should not show up in the dropdown menu when signing up for another showing.

**Comment by Edholm** [comment]
It shouldn't after a hard refresh. The state isn't updated in the frontend

**Comment by Kerp1** [comment]
Okay I signed up again and they were marked as pending, maybe I did something wrong the first time 👇

**Comment by lindskogen** [comment]
@Edholm This might be an outdated issue in that case, a fix for this should be in `master`.

**Comment by Edholm** [comment]
hehe might be but not verified though

**Comment by Edholm** [comment]
This problem exists in the current master branch as well.

**Comment by Dr-Horv** [comment]
This should be resolved in #149
