### ISSUE TITLE
Removing used company ticket

### ISSUE THREAD

**Issue by Kerp1** [cthdidIT/itbio#144]
When removing a used company ticket from my profile, i get this screen
![2017-09-13-110011_2019x1330_scrot](https://user-images.githubusercontent.com/4082428/30368858-cb4b188c-9872-11e7-850f-10bcceb96fdc.png)
when I refresh the page the company ticket was not removed.

**Comment by Dr-Horv** [comment]
This should be resolved in #149. Please reopen if not.
