### ISSUE TITLE
404 - page

### ISSUE THREAD

**Issue by Dr-Horv** [cthdidIT/itbio#16]
- [ ] Image asset
- [x] 3D asset
- [ ] 3D rendering of cinema

**Comment by Edholm** [comment]
Pretty sure this is fixed and/or not needed anymore

**Comment by Dr-Horv** [comment]
No, it's the 3D Alfons Easter egg

**Comment by lindskogen** [comment]
Is solved in 767c06f63be5454b76047175b12b0928332be443
