### ISSUE TITLE
Synced calendar events

### ISSUE THREAD

**Issue by juiceit** [cthdidIT/itbio#173]
As a user, I would like the possibility to add an event to my calendar from the moment I sign up for a showing in order to keep track of which day I'm probably busy. If the time changes once SF releases the tickets, I want my calendar to be updated.

We could start with an "add to calendar" button that shows up once you've signed up. Maybe add a setting later for automatically adding all events to your calendar. (I would like them all in there, but that might not be true for everyone.)

**Comment by Edholm** [comment]
Semi-fixed in latest `feature/graphql` branch. Now users can subscribe to a personal ical feed.
