### ISSUE TITLE
Promote to admin

### ISSUE THREAD

**Issue by Edholm** [cthdidIT/itbio#200]
Allow the admin of a showing to promote or switch another user to admin status. 

Is useful if the admin is unable to book the showing or is unable to attend the showing.

**Comment by Edholm** [comment]
Frontend left

**Comment by lindskogen** [comment]
Needs more testing, but initial support merged in 5503c70

**Comment by lindskogen** [comment]
Closed by 0781b18c064e1c50f35f2031ce4aa1d667d809db
