### ISSUE TITLE
"Popcorn" favicon

### ISSUE THREAD

**Issue by lindskogen** [cthdidIT/itbio#22]

**Comment by Edholm** [comment]
I guess this is not relevant anymore since @juiceit fixed a nice looking favicon?

**Comment by lindskogen** [comment]
Would still like #23 though

**Comment by Edholm** [comment]
![image](https://user-images.githubusercontent.com/1151328/27950342-38b42384-6301-11e7-866d-6e98c0aa01c6.png)
