### ISSUE TITLE
Update all links to filmstaden.se

### ISSUE THREAD

**Issue by lindskogen** [cthdidIT/itbio#251]
sf.se is now filmstaden.se 

- [x] sfBuyLink should use new domain
- [x] Update our text references to 'Filmstaden'
- [x] Various API requests
- [ ] Ticket URL validation

**Comment by Dr-Horv** [comment]
https://github.com/cthdidIT/itbio/pull/305

**Comment by lindskogen** [comment]
Closed by #305
