### ISSUE TITLE
Attendees doesn't provide bioklubbkortsnummer

### ISSUE THREAD

**Issue by Dr-Horv** [cthdidIT/itbio#61]
The attendee model doesn't send bioklubbkortsnummer making it hard to create a payment summary

**Comment by Dr-Horv** [comment]
Test comment

**Comment by Dr-Horv** [comment]
@lindskogen Fixed?

**Comment by lindskogen** [comment]
Closed by 56f5bebf1ee4cf5d70af9d098faf9d2fd94cdb65
