### ISSUE TITLE
Sort showings by date, earliest to last.

### ISSUE THREAD

**Issue by Tejpbit** [cthdidIT/itbio#79]
I'm guessing they are currently ordered by the time they were created.
Just sort them by earliest to last date.

![image](https://cloud.githubusercontent.com/assets/6124487/26057416/df17ca8e-3979-11e7-99c3-cc98725a163c.png)

**Comment by Edholm** [comment]
Fixed in 4c20f53a4dcb066070000f1b5c6ccde35487838a. @lindskogen confirm?

**Comment by lindskogen** [comment]
Confirmed
