### ISSUE TITLE
Upgrade to create-react-app v1.0

### ISSUE THREAD

**Issue by lindskogen** [cthdidIT/itbio#81]

**Comment by Edholm** [comment]
The app is already created, so why does this matter?

**Comment by lindskogen** [comment]
Tree shaking: https://webpack.js.org/guides/tree-shaking/

**Comment by Edholm** [comment]
fancy!

**Comment by lindskogen** [comment]
Fixed in 94d891816f35ae7e19642d6205c7257c3e7bd2c6
